server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # Enable and expose all endpoints

#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#      - "qa"
#
#build:
#  version: "3.0"
#
#
#cards:
#  message: "Welcome to Cards Service"
#  contact:
#    name: "Laith Hamdan"
#    email: "laith.hamdan@gmail.com"
#  onCallSupport:
#    - (222) 123-4567
#    - (333) 567-8901