spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      server:
        webflux:
          discovery:
            locator: # This will enable service discovery for routes in the gateway server
              enabled: false
              lower-case-service-id: true
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

info:
  app:
    name: "Gateway Server"
    description: "Gateway Server for banking app"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*" # Enable and expose all endpoints
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics: # The Purpose of this is to add tags to the metrics to make it easier to filter and monitor the metrics
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      yzn:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10 # Number of calls to change the state of the circuit breaker from closed to open
        permitted-number-of-calls-in-half-open-state: 2 # Allow 2 requests in half-open state, and based on the response of these requests, the circuit breaker will change its state
        failure-rate-threshold: 50  # If 50% of the requests fail, the circuit breaker will change its state from closed to open
        wait-duration-in-open-state:
          seconds: 10   # Wait for 10 seconds before changing the state of the circuit breaker from open to half-open

