server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*" # Enable and expose all endpoints
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: "unrestricted"
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics: # The Purpose of this is to add tags to the metrics to make it easier to filter and monitor the metrics
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "Loans Service"
    description: "Bank Loans Service"
    version: "1.0.0"


logging:
  level:
    com:
      yzn:
        loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#      - "prod"


#build:
#  version: "3.0"
#
#
#loans:
#  message: "Welcome to loans service"
#  contact:
#    name: "Ahmad Mahmoud"
#    email: "ahmad.mahmoud@gmail.com"
#  onCallSupport:
#    - (321) 354-546
#    - (452) 546-981


