server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*" # Enable and expose all endpoints
  endpoint:
    shutdown:
      access: "unrestricted"
  info:
    env:
      enabled: true

info:
  app:
    name: "Loans Service"
    description: "Bank Loans Service"
    version: "1.0.0"


#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#      - "prod"


#build:
#  version: "3.0"
#
#
#loans:
#  message: "Welcome to loans service"
#  contact:
#    name: "Ahmad Mahmoud"
#    email: "ahmad.mahmoud@gmail.com"
#  onCallSupport:
#    - (321) 354-546
#    - (452) 546-981
