spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: "native" # only for class path and file system locations
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/YznAlqadery/bank-config.git"
          default-label: main # Helpful if you have multiple branches
          timeout: 5 # Wait for 5 seconds for the config server to start
          clone-on-start: true # Clone the repository when the server starts in the local system
          force-pull: true # Force pull the repository when the server starts
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#        native:
#          #search-locations: "classpath:/config"
#          search-locations: "file:///C://Users//yazan//Documents//config" # File system path

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics: # The Purpose of this is to add tags to the metrics to make it easier to filter and monitor the metrics
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

encrypt:
  key: ${SECRET_KEY}

server:
  port: 8071
